### ISSUE TITLE
Event Metric not displying

### ISSUE THREAD

**Issue by adambarnett52** [grafana/grafana-sensu-app#11]
Hi, 
I have installed the plugin and in the supplied dashboard the "Sensu Events" table populates but anything that uses Event Metric never populates. it just sits this with the little spinning wheel for a while and then i get "No data points" for some  ( Active events widget) 
I can see that APi call and if i look a the query inspector i can see that data be returned

Am i missing something?

**Comment by briangann** [comment]
Which version of Sensu are you running?
With v1.6.2-2 I get results for all of the panels in the "Sensu Summary" dashboard.

**Comment by adambarnett52** [comment]
Hi

We are using an old version 0.20

Which fields is the plugin looking for in the API

Thanks
Adam

**Comment by briangann** [comment]
Looking at the output for v0.29 vs 1.6 the fields looks the same, but I don't know about v0.20.

Can you send the api responses you see in chrome dev tools?  (anonymized as needed)

The datasource pulls down /events/clientname and /events/clientname/check.

**Comment by adambarnett52** [comment]
Here is the response when looking in the Qurey Inspector 

```
	response: Array[42]
	0: Object
	1: Object
	2: Object
	  id: "ea82d173-04be-4691-b1c2-7d3b04855291"
	  client: Object
	   name: "playback21"
	   address: "unknown"
	    subscriptions: Array[0]
	   keepalives: false
	   version: "0.20.3"
	   check: Object
	     command: "perl /etc/sensu/plugins/dneg-github/check_infortrend.pl -H playback21raid"
	     handlers: Array[1]
	   interval: 1800
	   priority: "critical"
	   source: "playback21"
	   standalone: false
	   subscribers: Array[1]
	   name: "playback21raid"
	   issued: 1548327217
	   executed: 1548327217
	   duration: 3.114
	   output: "infortrend UNKNOWN - playback21raid is not supported by this plugin (or SNMP is taking a long time to respond) "
	   status: 3
	     history: Array[21]
	   total_state_change: 0
	   occurrences: 34
	   action: "create"
	   timestamp: 1548327220
```

**Comment by adambarnett52** [comment]
Updated to new version of sensu 1.7
