### ISSUE TITLE
Not honouring occurrence threshold

### ISSUE THREAD

**Issue by linuxprofessor** [grafana/grafana-sensu-app#12]
When utilising occurrences in Sensu I set something like 30 occurrences before a high load alarm is triggered.

It would be beneficial to have this kind of behaviour in the Grafana Sensu app too, since we're currently seeing a lot of, what we consider to be, false positives.

**Comment by briangann** [comment]
Just to verify - you want to be able to have a threshold based on occurrences and state?

**Comment by linuxprofessor** [comment]
I want to be able to not show issues that haven't exceeded the threshold.

If I have a CPU warning set at 80%, an interval of 60 seconds and a threshold of 30, the alarm shouldn't be raised until 30 checks have had a value of 80+%. This is the way it works in uchiwa where you can set it to hide alarms beflow occurrence threshold.

**Comment by briangann** [comment]
This project has been archived and no longer being developed.
