### ISSUE TITLE
Not display for one instant 

### ISSUE THREAD

**Issue by adambarnett52** [grafana/grafana-sensu-app#13]
Hi

I have 4 sensu servers running 1.7 and on 3 i can get the data from them
For one of them the widget in grafana never draws and it just sits there spinning
If i looks in the query inspector it shows the correct data

Any suggestions

**Comment by adambarnett52** [comment]
Forgot to add

Datasource: Sensu Server 
Source Type: Event Metrics
Event Metric Mode: Critical Active Count
Alias: Critical

**Comment by briangann** [comment]
I haven't tried with that many Sensu servers.

I'll set up a couple more and see what is going on.

**Comment by adambarnett52** [comment]
It seems odd, i have added each sensu server as a different data source, so some are working and some are not
Is there logs in grafana that would highlight why it is not working

**Comment by adambarnett52** [comment]
Just to add some more observations

On the instants that i cannot get the graph for i can actually see the alert when i have a table with the source type: Events as JSON 

It ssems when i do a single stat or pie chat it does not render the the images

**Comment by adambarnett52** [comment]
any suggestions here ?
