### ISSUE TITLE
Unable to Filter based on Check name

### ISSUE THREAD

**Issue by nshah011393** [grafana/grafana-sensu-app#14]
Running sensu-1.7.0-2 with the grafana-sensu 1.3 version and Grafana version 5.x+.

If I load the Source Type as "Results as JSON", with a "Table" Panel, I see all the JSON data properly. If I choose "Dimension" to be "Client Name", I can filter properly. However, if I choose "Check Name", the drop down list populates with all the proper checks, but clicking any of them does not filter the JSON. It still shows the same (total) number of unfiltered entries. I also tried to type some purposely incorrect check name/random string of letters, and nothing filtered as well (full results still showed up).

Not able to see what may be the cause, unless it is something to do with the Sensu Version (sensu-1.7.0-2).

Side note, also tried regex under the "Filter" option with "Check Name RegEx" , but no luck as well. 

Everything else is working wonderfully, but struggling with filtering based on "Check Name", and the use of "Regex" (I used regex for an "exact" match, but no luck)

Any pointers would be much appreciated.

**Comment by nshah011393** [comment]
Hello,

Just wanted to see if there was any clues found on this by chance? Or if anyone else has reported a similar issue?

Thanks!

**Comment by JonRGoode** [comment]
@nshah011393 
I have a similar issue except with Events as Json and filtering by Check name regex, I found the issue:
https://github.com/grafana/grafana-sensu-app/blob/master/src/datasource/sensu-core/api/event_filters.ts
doesn't have the code for filtering by regex, so if you try it'll return false for every item that passes through (return false == no match)
Also I am pretty sure that:
https://github.com/grafana/grafana-sensu-app/blob/master/src/datasource/sensu-core/query_ctrl.ts
Needs to have a "type" property set for the regex to to work, but I may have missed the code that determines the 'type' of the filter in a different way.

**Comment by briangann** [comment]
have been tied up with many other plugins, going to circle back here and resolve these problems.

**Comment by briangann** [comment]
This project has been archived and no longer being developed.
