### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by matthew-hollick** [grafana/grafana-sensu-app#2]
Hi,

This looks like it could be a really useful feature which we would definitely use.
Do you have an idea when it will be production ready? Maybe we can help with testing, documentation or even dare I suggest it, some code?

Regards,

Matthew

**Comment by briangann** [comment]
There's a PR in progress to enable more functionality. The app will be published hopefully over the next week. I've been refactoring into reactjs and bug fixing from the original source code.

Code/docs/testing are always welcome :)

**Comment by briangann** [comment]
@matthew-hollick the plugin is ready to use, you can install it via grafana-cli, or download from here: https://grafana.com/plugins/grafana-sensu-app

**Comment by matthew-hollick** [comment]
That's brilliant :-)
I'm going to open a PR to get it added into our infrastructure and shall let you know how it goes.

**Comment by matthew-hollick** [comment]
Hi,
we have deployed the sensu plugin to all environment.

Nice.

I'm having trouble getting filters to work, we have hostnames like `sensu_i-00ea4db35744210a4` I want to create a table that will only include hostnames like `^sensu.*` but I can't find the magic to do it.

**Comment by briangann** [comment]
This project has been archived and no longer being developed.
